#!/bin/bash
# Create a new factor using tools/move_info_along_ali.pl for the *source* corpus# by bringing in information from the target

set -o pipefail
function die() { echo "$@" | tee FAILED >&2; exit 1 ; }

eman \
  defvar ALISTEP default='' type=optstep \
    help="the step where alignment was constructed, implied by ALICORP+ALISYM+ALILABEL" \
  defvar SRCCORP inherit=ALISTEP:CORPUS \
    help="source corpus name" \
  defvar TGTCORP same_as=SRCCORP help="target corpus name, can be omitted if equal to SRCCORP" \
  defvar SRCAUG help="the string describing lang+factors of src corpus" \
  defvar TGTAUG help="the string describing lang+factors of tgt corpus" \
  defvar ALICORP same_as=SRCCORP help="alignment corpus name, can be omitted if equal to SRCCORP" \
  defvar ALISYM default='int' help='which alignment to use for the translation model' \
  defvar ALILABEL inherit=ALISTEP \
    help="the custom label as given when creating the alignment" \
  defvar ALIORREVALI default='ali' \
    help="set to 'ali' for standard usecase but to 'revali' for revgdfa etc." \
  defvar THRESHOLD default='' help="a+e, a-e of a number (see moses/sigtest-filter)" \
  defvar NBESTOOV default='' help="output n-best lexical entries in reduce-oov.pl (0 = output all)" \
  defvar CUTOFF default=0 help="phrase-table cutoff" \
  defvar EMAN_MEM default='6g' help="memory limit at cluster" \
  defvar EMAN_DISK default='20g' help="required free space at temp" \
|| exit 1

eval `eman bash-loadvars`

PLAYGROUND=`eman path`

if [ -z "$ALISTEP" ]; then
  echo "Finding alistep that provides $ALICORP/$ALISYM-$ALILABEL+ali"
  eval $($PLAYGROUND/corpman $ALICORP/$ALISYM-$ALILABEL+ali --init --bashvars=ALISTEP=stepname)
  export ALISTEP
  echo "Found ALISTEP=$ALISTEP"
  eman add-dep . "$ALISTEP" || die "Failed to depend on alistep $ALISTEP"
  eman defvar ALISTEP
fi

# check (if the alistep is indeed an align step and not a trick like idali)
# whether the corpus matches
KNOWNALICORPUS=$(eman getvar $ALISTEP CORPUS | perl -pe 's/^"(.*)"$/$1/')
[ "$KNOWNALICORPUS" == "$SRCCORP" ] \
  || [ "$KNOWNALICORPUS" == "" ] \
  || die "Nonmatching alistep: different corpus: $KNOWNALICORPUS vs $SRCCORP"
KNOWNALILABEL=$(eman getvar $ALISTEP ALILABEL | perl -pe 's/^"(.*)"$/$1/')
[ "$KNOWNALILABEL" == "$ALILABEL" ] \
  || [ "$KNOWNALILABEL" == "" ] \
  || die "Nonmatching alistep: different ALILABEL: $KNOWNALILABEL vs $ALILABEL"

BINARIESDIR=`eman path $BINARIES`
SCRIPTS_ROOTDIR="$BINARIESDIR/moses/scripts"

if echo "$DECODINGSTEPS" | grep , ; then
  echo "\$DECODINGSTEPS ($DECODINGSTEPS) contains a comma! Use 'a' instead, e.g. 0a1-0+1-1"
  exit 1
fi

DECRYPT=$PLAYGROUND/tools/decrypt_mapping_steps_for_training.pl
[ -x $DECRYPT ] || die "Missing: $DECRYPT"

DECRYPTEDSTEPS=`eval $DECRYPT $DECODINGSTEPS`
[ ! -z "$DECRYPTEDSTEPS" ] \
  || die "Failed to decrypt decoding steps $DECODINGSTEPS"

# Stop here if we are just initing ourselves
[ -z "$INIT_ONLY" ] || exit 0

cat << KONEC > eman.command
# This is the command to be run here
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

# If local copy of input files already exists (we are running 'eman continue') remove it first.
rm -rf corpus* alignment* model*

function mkcorpus() {
  $PLAYGROUND/corpman --wait \$1 || die "Failed to prepare \$1"
  step_file_col=(\$($PLAYGROUND/corpman \$1))
  if [ "\${step_file_col[2]}" == "-1" ]; then
    STEPPATH=\$(eman path \${step_file_col[0]})
    $PLAYGROUND/../scripts/wiseln \$STEPPATH/\${step_file_col[1]} \\
      \$2.gz \
    || die "Failed to clone \$2 corpus \$1"
  else
    echo "Selecting the column from \$step_file_col"
    eval \$($PLAYGROUND/corpman --cmd \$1) \\
    | gzip -c > \$2.gz
  fi
}

## Prepare the corpus from more factors
export SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR
echo SCRIPTS_ROOTDIR=$SCRIPTS_ROOTDIR

mkdir corpus

cd corpus
mkcorpus $SRCCORP/$SRCAUG corpus.src
mkcorpus $TGTCORP/$TGTAUG corpus.tgt
cd ..

mkcorpus $ALICORP/$ALISYM-$ALILABEL+ali alignment.orig
# we can't rely on the factor revali because concatenated corpora like
# c-news+c-fiction/foo+revali would be attempted per parts
if [ "$ALIORREVALI" == revali ]; then
  echo "Reversing the alignment..."
  zcat alignment.orig.gz \\
  | ../../scripts/reverse_alignment.pl \\
  | gzip -c > alignment.custom.gz
else
  ln -s alignment.orig.gz alignment.custom.gz
fi

alilen=\`zcat alignment.custom.gz | wc -l\`
srclen=\`zcat corpus/corpus.src.gz | wc -l\`
tgtlen=\`zcat corpus/corpus.tgt.gz | wc -l\`
if [[ \$alilen -ne \$srclen ]] \\
   || [[ \$alilen -ne \$tgtlen ]] \\
; then
  echo "Incompatible corpus lengths:"
  echo "\$alilen  alignment.custom.gz"
  echo "\$srclen  corpus.src.gz"
  echo "\$tgtlen  corpus.tgt.gz"
  die "Dying for incompatible corpus lengths"
fi

mkdir model

maintempdir=/mnt/h/tmp
[ -d \$maintempdir ] || maintempdir=/tmp

tempdir=\`mktemp -d \$maintempdir/exp.model.XXXXXX\`
echo "COPYING SELF TO TEMPDIR: \$tempdir"
rsync -avz --exclude 'log*' --exclude '*.hardlink' * \$tempdir/ \\
  || die "Failed to rsync"
echo "COPIED, used disk space:"

df \$tempdir

function reduce_oov {
  if [ -n "$NBESTOOV" ]; then
    echo "Now will reduce phrase-table OOV" \\
    && $PLAYGROUND/tools/reduce-oov.pl \\
      --extract-outdir \$tempdir/model \\
      --scripts-rootdir \$SCRIPTS_ROOTDIR \\
      --output-alignments \\
      --nbest $NBESTOOV \\
      --output-dir \$tempdir/reduce-oov \\
      --temp-dir /mnt/h/tmp \\
    && mv \$tempdir/reduce-oov/* \$tempdir/model
  fi
}

if \\
  \$SCRIPTS_ROOTDIR/training/train-model.perl \\
        --force-factored-filenames \\
	    --first-step 4 --last-step 6 \\
	    --root-dir \$tempdir \\
	    --alignment-file=alignment \\
	    --alignment=custom \\
	    --corpus=corpus/corpus \\
	    --f src --e tgt \\
        $TRAININGFLAGS \\
	    $DECRYPTEDSTEPS \\
  && echo "Now will filter translation models" \\
  && reduce_oov \\
  && $PLAYGROUND/tools/filter-several-phrasetables.pl \\
        --srccorp=$SRCCORP --srcaug=$SRCAUG \\
        --tgtcorp=$TGTCORP --tgtaug=$TGTAUG \\
        --cutoff=$CUTOFF --threshold=$THRESHOLD \\
        --workspace=$BINARIESDIR \\
        \$tempdir/model/phrase-table.* \\
  && echo "Now will extract generation models" \\
  && \$SCRIPTS_ROOTDIR/training/train-model.perl \\
        --force-factored-filenames \\
	    --first-step 8 --last-step 8 \\
	    --root-dir \$tempdir \\
	    --alignment-file=alignment \\
	    --alignment=custom \\
	    --corpus=corpus/corpus \\
	    --f src --e tgt \\
        $TRAININGFLAGS \\
	    $DECRYPTEDSTEPS \\
; then
  success=1
  rm -f \$tempdir/model/extract* # delete temporary files of extracted phrases
  echo "COPYING TEMPDIR \$tempdir BACK"
  rsync -uavz \$tempdir/* ./ || die "Assumed success but rsync back failed"
  echo "COPIED"

  echo Deleting \$tempdir
  rm -rf \$tempdir
else
  success=0
  rsync -uavz \$tempdir/log* ./ || die "Failure, and rsync back failed"
  echo "ONLY log copied back. Majority of files left here: \$tempdir"
fi

[ \$success == 1 ] || die "THERE WERE ERRORS!! See above."

echo "Getting phrase counts..."
( $PLAYGROUND/tools/zwc -l model/*.gz | tee phrase-counts ) || die "Failed to count phrases"

if [ 0 == \$(cut -f1 phrase-counts) ]; then
  die "Empty ttable, perhaps full temp disk above?"
fi

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
