#!/bin/bash
# eman seed for compiling fast-align

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# no vars
touch eman.vars

cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

git clone git://github.com/clab/fast_align.git || die "Failed to clone fast-align"
cd fast_align || die "Failed to chdir to fast_align"
make || die "Failed to compile"
cd ../ || die "chdir back failed"

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
