#!/bin/bash
# eman seed for constructing an n-gram language model
# binarization now excluded, because there are different (KenLM/IrstLM)
# binarization options

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

PLAYGROUND=`eman path` # eman playground directory

# Ensure all the required variables are set (or provide the default)
eman \
  defvar SRILMSTEP type=reqstep help='where is srilm compiled' \
  defvar CORP help='the shortname of corpus' \
  defvar CORPAUG help='the language+factors for the lm' \
  defvar ORDER help='the lm order' \
  defvar PARTS default='1' help='build a huge lm in N parts' \
  defvar LMFLAGS default='' help='flags for ngram-count like -unk' \
  defvar EMAN_MEM default='6g' help="memory limit at cluster" \
  defvar EMAN_DISK default='20g' help="required free space at temp" \
|| exit 1

# Set local bash variables
eval `eman bash-loadvars`

# add source corpus to deps
corpstep=$($PLAYGROUND/corpman --init $CORP/$CORPAUG | cut -f1)
[ ! -z "$corpstep" ] || die "Missing source corpus"

eman add-deps . $corpstep

# Stop here if we are just initing ourselves
[ -z "$INIT_ONLY" ] || exit 0

# Emit the main script to be used in the running phase

KNDISCOUNTSFROMTHREE=`seq 3 $ORDER | sed 's/\(.*\)/-kndiscount\1/' | tr '\n' ' '`

tempdir=/mnt/h/tmp
  # best choice for ufal
[ -d $tempdir ] || tempdir=/tmp
  # the default

# convert the dependencies to absolute paths
SRILMDIR=`eman path $SRILMSTEP`

cat << KONEC > eman.command
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

# init grid environment; sometimes needed for ./augment.pl
. /net/projects/SGE/user/sge_profile

SRILMDIR1="\$(cat $SRILMDIR/srilm.path)/bin/"
SRILMDIR2="\$(cat $SRILMDIR/srilm.path)/bin/i686/"

export PATH=\$SRILMDIR1:\$SRILMDIR2:\$PATH

echo "Using this ngram-count:"
which ngram-count || die "No ngram-count"
echo "Using this make-big-lm:"
which make-big-lm || die "No make-big-lm"

function mkcorpus() {
  # If local copy of corpus already exists (we are running 'eman continue') remove it first.
  rm -f corpus.\$2.gz
  corpspec=\$($PLAYGROUND/corpman --wait \$1)
  echo "corpman for \$1 returned: \$corpspec" # for the logfile
  step_file_col=(\$corpspec)
  corpfile=\$(eman path \${step_file_col[0]})/\${step_file_col[1]}
  [ -e \$corpfile ] \\
    || die "Failed to prepare \$1, corpus file not found: \$corpfile"
  if [ "\${step_file_col[2]}" == "-1" ]; then
    $PLAYGROUND/../scripts/wiseln \$corpfile \\
      corpus.\$2.gz \
    || die "Failed to clone \$2 corpus \$1"
  else
    echo "Selecting the column \${step_file_col[2]} from \$corpfile"
    zcat \$corpfile | cut -f "\${step_file_col[2]}" \\
    | gzip -c > corpus.\$2.gz
  fi
}

mkcorpus $CORP/$CORPAUG text

echo Generating model from corpus...
if [ $PARTS == 1 ]; then
  echo "Simple counting"
  if zcat corpus.text.gz | ngram-count -order $ORDER \\
    -text - \\
    -lm corpus.lm \\
    $LMFLAGS \\
    -interpolate -kndiscount; then
    echo "Succeeded."
  else
    echo Second attempt, skip bigrams in knsmoothing
    zcat corpus.text.gz | ngram-count -order $ORDER \\
      -text - \\
      $LMFLAGS \\
      -lm corpus.lm \\
      -interpolate $KNDISCOUNTSFROMTHREE \\
    || die "ngram-count FAILED even with bigrams not knsmoothed"
  fi
else
  partstempdir=\$(mktemp -d $tempdir/exp.lm.XXXXXX)
  echo Counting in $PARTS parts, tempdir=\$partstempdir
  zcat corpus.text.gz | split_even $PARTS \$partstempdir/part --gzip \
  || die "Splitting FAILED"
  ls \$partstempdir/part*.gz > \$partstempdir/filelist

  echo Making batch counts
  make-batch-counts \$partstempdir/filelist 1 zcat \$partstempdir \\
    -order $ORDER \\
    $LMFLAGS \\
    -interpolate -kndiscount \\
    || die "make-batch-counts FAILED"

  echo Merging batch counts
  merge-batch-counts \$partstempdir \\
    || die "merge-batch-counts FAILED"

  make-big-lm -read \$partstempdir/*.ngrams.gz \\
    -name \$partstempdir/biglm \\
    -order $ORDER \\
    $LMFLAGS \\
    -interpolate -kndiscount \\
    -lm \`pwd\`/corpus.lm \\
    || die "make-big-lm FAILED"

  echo Removing \$partstempdir
  rm -rf \$partstempdir
fi

echo Gzipping corpus.lm
gzip corpus.lm || die "Failed to gzip"

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
