#!/bin/bash
# eman seed for compiling mgiza

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# no vars
touch eman.vars

cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte


tar xzf ../../src/mgizapp-0.7.2.tar.gz || die "mgiza missing"
cd mgizapp || die "Failed to chdir to mgizapp"
./configure || die "Failed to configure"

#stupid patch... it can be done more beautifully but this will do :-)
cat src/Makefile | sed 's/-lpthread/-lpthread -lboost_thread/'>src/Makefile_copy
mv src/Makefile_copy src/Makefile

make || die "Failed to make"
cd ../ || die "chdir back failed"

mkdir -p bin || die "Can't make bindir"
ln -s ../mgizapp/src/mgiza ../mgizapp/src/snt2cooc \
   ../mgizapp/src/mkcls/mkcls ../mgizapp/src/symal ../mgizapp/scripts/merge_alignment.py  bin/
                                                   #the python script is not strictly "bin" but who cares

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
