#!/bin/bash
# eman seed for compiling moses

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

# Ensure all the required variables are set (or provide the default)
eman defvar SRILMSTEP default='' help='where is SRILM compiled, or empty' \
     defvar IRSTLMSTEP default='' help='where is IRSTLM compiled, or empty' \
     defvar REPOSITORY default='https://github.com/moses-smt/mosesdecoder.git' help='clone custom repository' \
     defvar BJAMARGS default=' --max-kenlm-order=12 -a ' help='any extra arguments for the compilation of Moses' \
     defvar BOOST default='' help='location of boost library' \
|| exit 1

# XXX we don't have any IRSTLM steps

# Set local bash variables
eval `eman bash-loadvars`

cat > eman.command << KONEC
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte


# Obtain GIZA++
tar xzf ../../src/giza-pp.tgz || die "giza-pp missing"
cd giza-pp || die "Failed to chdir to giza-pp"
## Not patching, otherwise giza often segfaults
#patch -p1 < ../../../src/giza-pp.patch-for-300words \
#  || die "Failed to patch GIZA"
patch -p1 < ../../../src/giza-pp.patch-against-binsearch \
  || die "Failed to patch GIZA"
cd GIZA++-v2 && make -j4 && make -j4 snt2cooc.out && cd ../ || die "GIZA failed"
cd mkcls-v2 && make -j4 && cd ../ || die "mkcls failed"
cd ../ || die "chdir back failed"

mkdir -p bin || die "Can't make bindir"
ln -s ../giza-pp/GIZA++-v2/GIZA++ ../giza-pp/GIZA++-v2/snt2cooc.out \
   ../giza-pp/mkcls-v2/mkcls bin/

# Obtain Moses
echo "Obtaining Moses"
git clone $REPOSITORY moses \\
|| die "Failed to clone moses"

cd moses || die "Chdir failed"

[ -z "$SRILMSTEP" ] || SRILMARG=" --with-srilm=\`eman path $SRILMSTEP\`/srilm "
[ -z "$IRSTLMSTEP" ] || IRSTLMARG=" --with-irstlm=\`eman path $IRSTLMSTEP\`/install "
BJAMARGS="$BJAMARGS "

BOOSTFLAG=""
if [ -n "$BOOST" ]; then
    BOOSTFLAG="--with-boost=$BOOST"
fi

./bjam -j4 --with-giza=\$mydir/bin \\
  \$SRILMARG \$IRSTLMARG \$BJAMARGS \$BOOSTFLAG || die "Build failed"
chmod -R a+rx .

cd ../ || die "chdir back failed"

cd bin || die "chdir to bin/ failed"
ln -s ../moses/bin/moses \\
   ../moses/bin/moses_chart \\
   ../moses/bin/symal \\
   ./ \\
|| die "symlinking failed"


# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
KONEC
