#!/bin/bash
# Download and compile Vowpal Wabbit

function die() { echo "$@" >&2; exit 1; }
set -o pipefail  # safer pipes

touch eman.vars 

cat > eman.command << END
#!/bin/bash
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
mydir=\$(pwd)
set -o pipefail
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }
renice 10 \$\$
ulimit -c 1 # core files limited to 1 byte

git clone git://github.com/hal3/vowpal_wabbit.git || die "Failed to clone VW"
cd vowpal_wabbit || die "Failed to chdir to vowpal_wabbit"
./autogen.sh --prefix=\$(pwd) || die "Configure failed"
make -j 8 || die "Compilation failed"
make install || die "Installation failed"

cd \$mydir || die "Failed to chdir back"

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
END
